apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-fe
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gracepark0120/sikseonsang.git
    targetRevision: HEAD
    path: fe
  destination: 
    server: https://kubernetes.default.svc
    namespace: fe

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
