apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: k8s-registry-test.kr.ncr.ntruss.com/nextjs-fe:latest
        name: fe
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
        env: # 컨테이너 환경 변수
        - name: UVICORN_CMD
          value: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
---
apiVersion: v1
kind: Service
metadata:
  name: fe
  labels:
    app: fe
spec:
  selector:
    app: fe
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
