apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-be
  namespace: argocd
spec:
  project: default

  source:
    repoURL:  https://gitlab.com/sikseonsang/k8s.git
    targetRevision: HEAD
    path: /be
  destination: 
    server: https://kubernetes.default.svc
    namespace: be

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
